name: OpenWrt-HiWiFi-1s

on:
  repository_dispatch:
  workflow_dispatch:

env:
  RESOURCE_DIR: /HiWiFi-1s

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-22.04

    steps:
      - name: Check Server Performance
        run: |
          echo "-------------------------- CPU INFO --------------------------"
          echo "CPU 物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU 核心数量：$(nproc)"
          echo -e "CPU 型号信息：$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "-------------------------- MEMORY INFO --------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "-------------------------- DISK INFO --------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -y install git

      - name: Checkout OpenWrt
        uses: actions/checkout@v4

      - name: Clone Source
        run: |
          source {GITHUB_WORKSPACE}${RESOURCE_DIR}/env.sh
          sudo mkdir /opt/openwrt
          sudo chown -R runner:runner /opt/openwrt
          git clone $REPOSITORY_URL /opt/openwrt
          ll /opt/openwrt
