name: OpenWrt-HiWiFi-1s

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  RESOURCE_DIR: /HiWiFi-1s

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-22.04

    steps:
      - name: Check Server Performance
        run: |
          echo "-------------------------- CPU INFO --------------------------"
          echo "CPU 物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU 核心数量：$(nproc)"
          echo -e "CPU 型号信息：$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "-------------------------- MEMORY INFO --------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "-------------------------- DISK INFO --------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Checkout OpenWrt
        uses: actions/checkout@v4

      - name: Clone Source
        run: |
          sudo mkdir /opt/openwrt
          sudo chown -R runner:runner /opt/openwrt
          git clone $REPO_URL /opt/openwrt

      - name: Load custom feeds
        run: |
          [ -e ${GITHUB_WORKSPACE}${RESOURCE_DIR}/feeds.conf.default ] && mv -f ${GITHUB_WORKSPACE}${RESOURCE_DIR}/feeds.conf.default /opt/openwrt/feeds.conf.default

      - name: Update feeds
        run: |
          /opt/openwrt/scripts/feeds update -a
          /opt/openwrt/scripts/feeds install -a

      - name: Configuration OpenWrt
        run: |
          mv -f ${GITHUB_WORKSPACE}${RESOURCE_DIR}/.config /opt/openwrt/.config
          [ -n "$(ls -A ${GITHUB_WORKSPACE}${RESOURCE_DIR})" ] && echo "AAAA"
